version: '3.7'

services:
  bot:
    build:
      dockerfile: Dockerfile
      context: ./telegram_bot
    restart: unless-stopped
    volumes:
      - ./telegram_bot:/bot
    depends_on:
      - app
  app:
    build: .
    container_name: fisheye_app
    ports:
      - "8765:8765"
    restart: unless-stopped
    volumes:
      - ./static:/app/static
      - ./backup:/app/backup
      - ./frontend:/app/frontend
    depends_on:
      - db
  db:
    image: postgres:13
    container_name: fisheye_db
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust

volumes:
  postgres_data:
