# Generated by Django 4.0.4 on 2022-05-28 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='filternode',
            unique_together={('filter', 'index')},
        ),
    ]
