# Generated by Django 4.0.4 on 2022-05-27 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0002_microservice_alter_filter_name_alter_node_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='microservice',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
