# Generated by Django 4.0.4 on 2022-05-28 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0003_filternode_default_json_params_node_req_fields_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filternode',
            name='default_json_params',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
