# Generated by Django 4.0.4 on 2022-05-28 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0004_alter_filternode_default_json_params'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='req_fields',
            field=models.TextField(default='image_base64,text', help_text='\n    allowed comma-separated request json data field names, example:\n    image_base64,text\n    '),
        ),
        migrations.AlterField(
            model_name='node',
            name='res_fields',
            field=models.TextField(default='image_base64,text', help_text='\n    allowed comma-separated response json data field names, example:\n    image_base64,text\n    '),
        ),
    ]
