# Generated by Django 4.0.4 on 2022-05-28 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0005_alter_node_req_fields_alter_node_res_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
