# Generated by Django 4.0.4 on 2022-05-28 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0007_alter_staticimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterBenchmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ms', models.PositiveBigIntegerField()),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nodes.filter')),
            ],
        ),
    ]
