# Generated by Django 4.0.4 on 2022-05-30 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0010_filternode_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='filterbenchmark',
            name='request_json',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='filterbenchmark',
            name='response_json',
            field=models.JSONField(default=dict),
        ),
    ]
