# Generated by Django 4.0.4 on 2022-05-30 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0012_filterbenchmark_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
